//priority: 200

// Listen to item tag event
onEvent('block.tags', event => {
    event.remove('forge:ores/gold', 'minecraft:gold_ore')
    event.remove('forge:ores', 'minecraft:gold_ore')
    event.remove('forge:ores/iron', 'minecraft:iron_ore')
    event.remove('forge:ores', 'minecraft:iron_ore')
    event.remove('forge:ores/coal', 'minecraft:coal_ore')
    event.remove('forge:ores', 'minecraft:coal_ore')
    event.remove('forge:ores/gold', 'minecraft:nether_gold_ore')
    event.remove('forge:ores', 'minecraft:nether_gold_ore')
    event.remove('forge:ores/lapis', 'minecraft:lapis_ore')
    event.remove('forge:ores', 'minecraft:lapis_ore')
    event.remove('forge:ores/diamond', 'minecraft:diamond_ore')
    event.remove('forge:ores', 'minecraft:diamond_ore')
    event.remove('forge:ores/redstone', 'minecraft:redstone_ore')
    event.remove('forge:ores', 'minecraft:redstone_ore')
    event.remove('forge:ores/emerald', 'minecraft:emerald_ore')
    event.remove('forge:ores', 'minecraft:emerald_ore')
    event.remove('forge:ores/quartz', 'minecraft:nether_quartz_ore')
    event.remove('forge:ores', 'minecraft:nether_quartz_ore')
/*
    event.remove('forge:ores/certus_quartz', 'appliedenergistics2:quartz_ore')
    event.remove('forge:ores', 'appliedenergistics2:quartz_ore')
    event.remove('forge:ores/certus_quartz', 'appliedenergistics2:charged_quartz_ore')
    event.remove('forge:ores', 'appliedenergistics2:charged_quartz_ore')
*/
    event.remove('forge:ores/copper', 'immersiveengineering:ore_copper')
    event.remove('forge:ores/aluminum', 'immersiveengineering:ore_aluminum')
    event.remove('forge:ores/lead', 'immersiveengineering:ore_lead')
    event.remove('forge:ores/silver', 'immersiveengineering:ore_silver')
    event.remove('forge:ores/nickel', 'immersiveengineering:ore_nickel')
    event.remove('forge:ores/uranium', 'immersiveengineering:ore_uranium')
    event.remove('forge:ores', 'immersiveengineering:ore_copper')
    event.remove('forge:ores', 'immersiveengineering:ore_aluminum')
    event.remove('forge:ores', 'immersiveengineering:ore_lead')
    event.remove('forge:ores', 'immersiveengineering:ore_silver')
    event.remove('forge:ores', 'immersiveengineering:ore_nickel')
    event.remove('forge:ores', 'immersiveengineering:ore_uranium')

    event.remove('forge:ores/cinnabar', 'thermal:cinnabar_ore')
    event.remove('forge:ores/apatite', 'thermal:apatite_ore')
    event.remove('forge:ores/niter', 'thermal:niter_ore')
    event.remove('forge:ores/sulfur', 'thermal:sulfur_ore')
    event.remove('forge:ores/copper', 'thermal:copper_ore')
    event.remove('forge:ores/tin', 'thermal:tin_ore')
    event.remove('forge:ores/lead', 'thermal:lead_ore')
    event.remove('forge:ores/silver', 'thermal:silver_ore')
    event.remove('forge:ores/nickel', 'thermal:nickel_ore')
    event.remove('forge:ores', 'thermal:cinnabar_ore')
    event.remove('forge:ores', 'thermal:apatite_ore')
    event.remove('forge:ores', 'thermal:niter_ore')
    event.remove('forge:ores', 'thermal:sulfur_ore')
    event.remove('forge:ores', 'thermal:copper_ore')
    event.remove('forge:ores', 'thermal:tin_ore')
    event.remove('forge:ores', 'thermal:lead_ore')
    event.remove('forge:ores', 'thermal:silver_ore')
    event.remove('forge:ores', 'thermal:nickel_ore')

    event.remove('forge:ores', 'mekanism:copper_ore')
    event.remove('forge:ores/copper', 'mekanism:copper_ore')
    event.remove('forge:ores', 'mekanism:tin_ore')
    event.remove('forge:ores/tin', 'mekanism:tin_ore')
    event.remove('forge:ores', 'mekanism:osmium_ore')
    event.remove('forge:ores/osmium', 'mekanism:osmium_ore')
    event.remove('forge:ores', 'mekanism:uranium_ore')
    event.remove('forge:ores/uranium', 'mekanism:uranium_ore')
    event.remove('forge:ores', 'mekanism:fluorite_ore')
    event.remove('forge:ores/fluorite', 'mekanism:fluorite_ore')
    event.remove('forge:ores', 'mekanism:lead_ore')
    event.remove('forge:ores/lead', 'mekanism:lead_ore')
/*
    event.remove('forge:ores/copper', 'electrodynamics:orecopper')
    event.remove('forge:ores/tin', 'electrodynamics:oretin')
    event.remove('forge:ores/silver', 'electrodynamics:oresilver')
    event.remove('forge:ores/lead', 'electrodynamics:orelead')
*/
    event.remove('forge:ores/copper', 'tconstruct:copper_ore')
    event.remove('forge:ores', 'tconstruct:copper_ore')
    event.remove('forge:ores/cobalt', 'tconstruct:cobalt_ore')
    event.remove('forge:ores', 'tconstruct:cobalt_ore')
/*
    event.remove('forge:ores/copper', 'libvulpes:orecopper')
    event.remove('forge:ores/tin', 'libvulpes:oretin')
    event.remove('forge:ores/aluminum', 'libvulpes:orealuminum')
*/
    event.add('forge:ores/niter', 'emendatusenigmatica:potassium_nitrate_ore')
    event.add('forge:ores/bitumen', 'thermal:oil_sand')
    event.add('forge:ores/bitumen', 'thermal:oil_red_sand')

    /*
    event.remove('forge:gears', 'thermal:iron_gear')
    event.remove('forge:gears/iron', 'thermal:iron_gear')
    event.remove('forge:gears', 'thermal:gold_gear')
    event.remove('forge:gears/gold', 'thermal:gold_gear')
    event.remove('forge:gears', 'thermal:lapis_gear')
    event.remove('forge:gears/lapis', 'thermal:lapis_gear')
    event.remove('forge:gears', 'thermal:diamond_gear')
    event.remove('forge:gears/diamond', 'thermal:diamond_gear')
    event.remove('forge:gears', 'thermal:emerald_gear')
    event.remove('forge:gears/emerald', 'thermal:emerald_gear')
    event.remove('forge:gears', 'thermal:quartz_gear')
    event.remove('forge:gears/quartz', 'thermal:quartz_gear')
    event.remove('forge:gears', 'thermal:copper_gear')
    event.remove('forge:gears/copper', 'thermal:copper_gear')
    event.remove('forge:gears', 'thermal:tin_gear')
    event.remove('forge:gears/tin', 'thermal:tin_gear')
    event.remove('forge:gears', 'thermal:lead_gear')
    event.remove('forge:gears/lead', 'thermal:lead_gear')
    event.remove('forge:gears', 'thermal:silver_gear')
    event.remove('forge:gears/silver', 'thermal:silver_gear')
    event.remove('forge:gears', 'thermal:nickel_gear')
    event.remove('forge:gears/nickel', 'thermal:nickel_gear')
    event.remove('forge:gears', 'thermal:bronze_gear')
    event.remove('forge:gears/bronze', 'thermal:bronze_gear')
    event.remove('forge:gears', 'thermal:electrum_gear')
    event.remove('forge:gears/electrum', 'thermal:electrum_gear')
    event.remove('forge:gears', 'thermal:invar_gear')
    event.remove('forge:gears/invar', 'thermal:invar_gear')
    event.remove('forge:gears', 'thermal:constantan_gear')
    event.remove('forge:gears/constantan', 'thermal:constantan_gear')
    event.remove('forge:gears', 'thermal:signalum_gear')
    event.remove('forge:gears/signalum', 'thermal:signalum_gear')
    event.remove('forge:gears', 'thermal:lumium_gear')
    event.remove('forge:gears/lumium', 'thermal:lumium_gear')
    event.remove('forge:gears', 'thermal:enderium_gear')
    event.remove('forge:gears/enderium', 'thermal:enderium_gear')

    event.remove('forge:gears', 'libvulpes:gearsteel')
    event.remove('forge:gears/steel', 'libvulpes:gearsteel')

    event.remove('forge:plates', 'libvulpes:plateiron')
    event.remove('forge:plates/iron', 'libvulpes:plateiron')
    event.remove('forge:plates', 'libvulpes:plategold')
    event.remove('forge:plates/gold', 'libvulpes:plategold')
    event.remove('forge:plates', 'libvulpes:platecopper')
    event.remove('forge:plates/copper', 'libvulpes:platecopper')
    event.remove('forge:plates', 'libvulpes:platetin')
    event.remove('forge:plates/tin', 'libvulpes:platetin')
    event.remove('forge:plates', 'libvulpes:platesteel')
    event.remove('forge:plates/steel', 'libvulpes:platesteel')
    event.remove('forge:plates', 'libvulpes:platealuminum')
    event.remove('forge:plates/aluminum', 'libvulpes:platealuminum')
    event.remove('forge:plates', 'libvulpes:platealuminum')
    event.remove('forge:plates/aluminum', 'libvulpes:platealuminum')

    event.remove('forge:ingots', 'immersiveengineering:ingot_steel')
    event.remove('forge:ingots/steel', 'immersiveengineering:ingot_steel')

    event.remove('forge:nuggets', 'immersiveengineering:nugget_steel')
    event.remove('forge:nuggets/steel', 'immersiveengineering:nugget_steel')

    event.remove('forge:plates', 'immersiveengineering:plate_steel')
    event.remove('forge:plates/steel', 'immersiveengineering:plate_steel')

    event.remove('forge:plates', 'immersiveengineering:plate_copper')
    event.remove('forge:plates/copper', 'immersiveengineering:plate_copper')
    event.remove('forge:plates', 'immersiveengineering:plate_aluminum')
    event.remove('forge:plates/aluminum', 'immersiveengineering:plate_aluminum')
    event.remove('forge:plates', 'immersiveengineering:plate_lead')
    event.remove('forge:plates/lead', 'immersiveengineering:plate_lead')
    event.remove('forge:plates', 'immersiveengineering:plate_silver')
    event.remove('forge:plates/silver', 'immersiveengineering:plate_silver')
    event.remove('forge:plates', 'immersiveengineering:plate_nickel')
    event.remove('forge:plates/nickel', 'immersiveengineering:plate_nickel')
    event.remove('forge:plates', 'immersiveengineering:plate_uranium')
    event.remove('forge:plates/uranium', 'immersiveengineering:plate_uranium')
    event.remove('forge:plates', 'immersiveengineering:plate_constantan')
    event.remove('forge:plates/constantan', 'immersiveengineering:plate_constantan')
    event.remove('forge:plates', 'immersiveengineering:plate_electrum')
    event.remove('forge:plates/electrum', 'immersiveengineering:plate_electrum')
    event.remove('forge:plates', 'immersiveengineering:plate_iron')
    event.remove('forge:plates/iron', 'immersiveengineering:plate_iron')
    event.remove('forge:plates', 'immersiveengineering:plate_gold')
    event.remove('forge:plates/gold', 'immersiveengineering:plate_gold')

    event.remove('forge:plates', 'thermal:iron_plate')
    event.remove('forge:plates/iron', 'thermal:iron_plate')
    event.remove('forge:plates', 'thermal:gold_plate')
    event.remove('forge:plates/gold', 'thermal:gold_plate')
    event.remove('forge:plates', 'thermal:copper_plate')
    event.remove('forge:plates/copper', 'thermal:copper_plate')
    event.remove('forge:plates', 'thermal:tin_plate')
    event.remove('forge:plates/tin', 'thermal:tin_plate')
    event.remove('forge:plates', 'thermal:lead_plate')
    event.remove('forge:plates/lead', 'thermal:lead_plate')
    event.remove('forge:plates', 'thermal:silver_plate')
    event.remove('forge:plates/silver', 'thermal:silver_plate')
    event.remove('forge:plates', 'thermal:nickel_plate')
    event.remove('forge:plates/nickel', 'thermal:nickel_plate')
    event.remove('forge:plates', 'thermal:bronze_plate')
    event.remove('forge:plates/bronze', 'thermal:bronze_plate')
    event.remove('forge:plates', 'thermal:electrum_plate')
    event.remove('forge:plates/electrum', 'thermal:electrum_plate')
    event.remove('forge:plates', 'thermal:invar_plate')
    event.remove('forge:plates/invar', 'thermal:invar_plate')
    event.remove('forge:plates', 'thermal:constantan_plate')
    event.remove('forge:plates/constantan', 'thermal:constantan_plate')
    event.remove('forge:plates', 'thermal:signalum_plate')
    event.remove('forge:plates/signalum', 'thermal:signalum_plate')
    event.remove('forge:plates', 'thermal:lumium_plate')
    event.remove('forge:plates/lumium', 'thermal:lumium_plate')
    event.remove('forge:plates', 'thermal:enderium_plate')
    event.remove('forge:plates/enderium', 'thermal:enderium_plate')

    event.remove('forge:rods', 'immersiveengineering:stick_steel')
    event.remove('forge:rods/steel', 'immersiveengineering:stick_steel')
    event.remove('forge:rods', 'immersiveengineering:stick_iron')
    event.remove('forge:rods/iron', 'immersiveengineering:stick_iron')
    event.remove('forge:rods', 'immersiveengineering:stick_aluminum')
    event.remove('forge:rods/aluminum', 'immersiveengineering:stick_aluminum')

    event.remove('forge:dusts', 'thermal:iron_dust')
    event.remove('forge:dusts/iron', 'thermal:iron_dust')
    event.remove('forge:dusts', 'thermal:gold_dust')
    event.remove('forge:dusts/gold', 'thermal:gold_dust')
    event.remove('forge:dusts', 'thermal:lapis_dust')
    event.remove('forge:dusts/lapis', 'thermal:lapis_dust')
    event.remove('forge:dusts', 'thermal:diamond_dust')
    event.remove('forge:dusts/diamond', 'thermal:diamond_dust')
    event.remove('forge:dusts', 'thermal:emerald_dust')
    event.remove('forge:dusts/emerald', 'thermal:emerald_dust')
    event.remove('forge:dusts', 'thermal:quartz_dust')
    event.remove('forge:dusts/quartz', 'thermal:quartz_dust')
    event.remove('forge:dusts', 'thermal:copper_dust')
    event.remove('forge:dusts/copper', 'thermal:copper_dust')
    event.remove('forge:dusts', 'thermal:tin_dust')
    event.remove('forge:dusts/tin', 'thermal:tin_dust')
    event.remove('forge:dusts', 'thermal:tin_dust')
    event.remove('forge:dusts/tin', 'thermal:tin_dust')
    event.remove('forge:dusts', 'thermal:lead_dust')
    event.remove('forge:dusts/lead', 'thermal:lead_dust')
    event.remove('forge:dusts', 'thermal:silver_dust')
    event.remove('forge:dusts/silver', 'thermal:silver_dust')
    event.remove('forge:dusts', 'thermal:nickel_dust')
    event.remove('forge:dusts/nickel', 'thermal:nickel_dust')

    event.remove('forge:dusts', 'libvulpes:dustiron')
    event.remove('forge:dusts/iron', 'libvulpes:dustiron')
    event.remove('forge:dusts', 'libvulpes:dustgold')
    event.remove('forge:dusts/gold', 'libvulpes:dustgold')
    event.remove('forge:dusts', 'libvulpes:dustcopper')
    event.remove('forge:dusts/copper', 'libvulpes:dustcopper')
    event.remove('forge:dusts', 'libvulpes:dusttin')
    event.remove('forge:dusts/tin', 'libvulpes:dusttin')
    event.remove('forge:dusts', 'libvulpes:duststeel')
    event.remove('forge:dusts/steel', 'libvulpes:duststeel')
    event.remove('forge:dusts', 'libvulpes:dustaluminum')
    event.remove('forge:dusts/aluminum', 'libvulpes:dustaluminum')

    event.remove('forge:sticks', 'libvulpes:sticksteel')
    event.remove('forge:sticks/steel', 'libvulpes:sticksteel')
    event.remove('forge:sticks', 'libvulpes:stickiron')
    event.remove('forge:sticks/iron', 'libvulpes:stickiron')
    event.remove('forge:sticks', 'libvulpes:stickcopper')
    event.remove('forge:sticks/copper', 'libvulpes:stickcopper')

    event.remove('forge:ores/copper', 'mekanism:copper_ore')
    event.remove('forge:ores/tin', 'mekanism:tin_ore')
    event.remove('forge:ores/osmium', 'mekanism:osmium_ore')
    event.remove('forge:ores/uranium', 'mekanism:uranium_ore')
    event.remove('forge:ores/fluorite', 'mekanism:fluorite_ore')
    event.remove('forge:ores/lead', 'mekanism:lead_ore')

    event.remove('forge:ores/cinnabar', 'thermal:cinnabar_ore')
    event.remove('forge:ores/niter', 'thermal:niter_ore')
    event.remove('forge:ores/sulfur', 'thermal:sulfur_ore')
    event.remove('forge:ores/copper', 'thermal:copper_ore')
    event.remove('forge:ores/tin', 'thermal:tin_ore')
    event.remove('forge:ores/lead', 'thermal:lead_ore')
    event.remove('forge:ores/silver', 'thermal:silver_ore')
    event.remove('forge:ores/nickel', 'thermal:nickel_ore')

    event.remove('forge:ores/copper', 'electrodynamics:ingotcopper')
    event.remove('forge:ores/tin', 'electrodynamics:ingottin')
    event.remove('forge:ores/silver', 'electrodynamics:ingotsilver')
    event.remove('forge:ores/steel', 'electrodynamics:ingotsteel')
    event.remove('forge:ores/lead', 'electrodynamics:ingotlead')
    event.remove('forge:ores/bronze', 'electrodynamics:ingotbronze')
    event.remove('forge:ores/vanadium', 'electrodynamics:ingotvanadium')

    event.remove('forge:gears/iron', 'electrodynamics:geariron')
    event.remove('forge:gears/copper', 'electrodynamics:gearcopper')
    event.remove('forge:gears/tin', 'electrodynamics:geartin')
    event.remove('forge:gears/steel', 'electrodynamics:gearsteel')
    event.remove('forge:gears/bronze', 'electrodynamics:gearbronze')

    event.remove('forge:plates/iron', 'electrodynamics:plateiron')
    event.remove('forge:plates/steel', 'electrodynamics:platesteel')
    event.remove('forge:plates/lead', 'electrodynamics:platelead')
    event.remove('forge:plates/bronze', 'electrodynamics:platebronze')

    event.remove('forge:dusts/iron', 'electrodynamics:dustiron')
    event.remove('forge:dusts/gold', 'electrodynamics:dustgold')
    event.remove('forge:dusts/copper', 'electrodynamics:dustcopper')
    event.remove('forge:dusts/tin', 'electrodynamics:dusttin')
    event.remove('forge:dusts/silver', 'electrodynamics:dustsilver')
    event.remove('forge:dusts/steel', 'electrodynamics:duststeel')
    event.remove('forge:dusts/lead', 'electrodynamics:dustlead')
    event.remove('forge:dusts/bronze', 'electrodynamics:dustbronze')
    event.remove('forge:dusts/endereye', 'electrodynamics:dustendereye')
    event.remove('forge:dusts/vanadium', 'electrodynamics:dustvanadium')
    event.remove('forge:dusts/sulfur', 'electrodynamics:dustsulfur')
    event.remove('forge:dusts/niter', 'electrodynamics:dustniter')
    event.remove('forge:dusts/obsidian', 'electrodynamics:dustobsidian')

    event.remove('forge:impuredusts/iron', 'electrodynamics:impuredustiron')
    event.remove('forge:impuredusts/gold', 'electrodynamics:impuredustgold')
    event.remove('forge:impuredusts/copper', 'electrodynamics:impuredustcopper')
    event.remove('forge:impuredusts/tin', 'electrodynamics:impuredusttin')
    event.remove('forge:impuredusts/silver', 'electrodynamics:impuredustsilver')
    event.remove('forge:impuredusts/lead', 'electrodynamics:impuredustlead')
    event.remove('forge:impuredusts/vanadium', 'electrodynamics:impuredustvanadium')

    event.remove('forge:ingots/copper', 'electrodynamics:ingotcopper')
    event.remove('forge:ingots/tin', 'electrodynamics:ingottin')
    event.remove('forge:ingots/silver', 'electrodynamics:ingotsilver')
    event.remove('forge:ingots/steel', 'electrodynamics:ingotsteel')
    event.remove('forge:ingots/lead', 'electrodynamics:ingotlead')
    event.remove('forge:ingots/bronze', 'electrodynamics:ingotbronze')
    event.remove('forge:ingots/vanadium', 'electrodynamics:ingotvanadium')
    */
    
    // Get #forge:ingots/copper tag and remove all entries from it
//    event.removeAll('forge:ingots/copper')

//    event.removeAll('forge:ingots/aluminum')
  })