onEvent("jei.information", jei_info => {
/*
    jei_info.add('quark:white_candle',['Makes the Matrix Enchanter more likely to give Unbreaking'])
    jei_info.add('quark:orange_candle',['Makes the Matrix Enchanter more likely to give Fire Protection'])
    jei_info.add('quark:magenta_candle',['Makes the Matrix Enchanter more likely to give Knockback and Punch'])
    jei_info.add('quark:light_blue_candle',['Makes the Matrix Enchanter more likely to give Feather Falling'])
    jei_info.add('quark:yellow_candle',['Makes the Matrix Enchanter more likely to give Looting, Fortune, and Luck of the Sea'])
    jei_info.add('quark:lime_candle',['Makes the Matrix Enchanter more likely to give Blast Protection'])
    jei_info.add('quark:pink_candle',['Makes the Matrix Enchanter more likely to give Silk Touch and Channeling'])
    jei_info.add('quark:gray_candle',['Makes the Matrix Enchanter more likely to give Bane of Arthopods'])
    jei_info.add('quark:light_gray_candle',['Makes the Matrix Enchanter more likely to give Protection'])
    jei_info.add('quark:cyan_candle',['Makes the Matrix Enchanter more likely to give Respiration, Loyalty, and Infinity'])
    jei_info.add('quark:purple_candle',['Makes the Matrix Enchanter more likely to give Sweeping and Multishot'])
    jei_info.add('quark:blue_candle',['Makes the Matrix Enchanter more likely to give Efficiency, Sharpness, Lure, Power, Impaling, and Quick Charge'])
    jei_info.add('quark:brown_candle',['Makes the Matrix Enchanter more likely to give Aqua Affinity, Depth Strider, and Riptide'])
    jei_info.add('quark:green_candle',['Makes the Matrix Enchanter more likely to give Thorns and Piercing'])
    jei_info.add('quark:red_candle',['Makes the Matrix Enchanter more likely to give Fire Aspect and Flame'])
    jei_info.add('quark:black_candle',['Makes the Matrix Enchanter more likely to give Smite and Projectile Protection'])
*/
    jei_info.add('tconstruct:dragon_scale',['Drops when the Ender Dragon is killed by an explosion'])
    jei_info.add('minecraft:ender_pearl',['Can be used to create the Quantum Entangled Singularity along with a Singularity and an explosion'])
})