tickDelay = 20
formatEMC = true
fullNumberNames = true
emcDisplay = true
notifyCommandChanges = true
limitEmcLinkVendor = true
transmutationInterfaceItemCount = 2147483647
useOldValues = false
collectorMultiplier = 1
emcLinkItemLimitMultiplier = 1
emcLinkEMCLimitMultiplier = 1
powerflowerMultiplier = 1
relayBonusMultiplier = 1
relayTransferMultiplier = 1
notifyKnowledgeBookGains = true
emcLinkFluidLimitMultiplier = 1
infiniteFuelCost = 128
infiniteFuelBurnTime = 1600
infiniteSteakCost = 64

