tickDelay = 20
formatEMC = true
fullNumberNames = true
emcDisplay = true
notifyCommandChanges = true
limitEmcLinkVendor = true
transmutationInterfaceItemCount = 2147483648
useOldValues = false
collectorMultiplier = 1
emcLinkItemLimitMultiplier = 1
emcLinkEMCLimitMultiplier = 1
powerflowerMultiplier = 1
relayBonusMultiplier = 1
relayTransferMultiplier = 1

